### ISSUE TITLE
I tried the testing branch but now TV show networks don’t show up on widgets

### ISSUE THREAD

**Issue by xyzfre** [SerpentDrago/skin.auramod#100] opened 2021-05-22 22:26 UTC
https://user-images.githubusercontent.com/49699869/119242313-ddd9ef80-bb2a-11eb-9db0-8284de711721.MOV

This is using the repo version of AuraMod Matrix using Fen and Venom widgets,, when I tried the testing  branch all the networks were missing from tv shows and Episodes,, for Movies the studio logo did work even with Fen which it didn’t before so that part is fixed on testing branch but once again the TV shows and episodes networks are missing,, I’ll put up a video in a few using the testing branch

**Comment by inb4after** [comment] 2021-05-22 22:46
> https://user-images.githubusercontent.com/49699869/119242313-ddd9ef80-bb2a-11eb-9db0-8284de711721.MOV
> 
> This is using the repo version of AuraMod Matrix using Fen and Venom widgets,, when I tried the testing  branch all the networks were missing from tv shows and Episodes I’ll put up a video in a few using the testing branch

So Matrix branch works, but Testing branch does not? Got confused by the video.

But it also happened to another tester. Testing branch requires the latest Github version of TMDBHelper, which should be version 4.3.7.

The update to TV network property was done only 2 days ago, so I don't think it's uploaded to jurial's repo yet, but you can install the zip manually from the matrix branch of TMDBHelper on Github. 

Hope this helps to fix this. I'll leave the issue open for now if anyone else has similar issues they will know what to do.

**Comment by xyzfre** [comment] 2021-05-22 23:04
It’s Working now on testing Branch thank you for the quick fix ,episodes and TV shows networks are working 👌🏼GREAT WORK✊🏼

**Comment by xyzfre** [comment] 2021-05-22 23:08
Not trying to be a bother but just noticed now on testing Branch movie studio logos are not showing up but prior to this fix they were working on testing Branch

**Comment by xyzfre** [comment] 2021-05-22 23:11
https://user-images.githubusercontent.com/49699869/119243053-6fe4f680-bb31-11eb-80ba-8e78b8f7bdea.MOV

Testing Branch

**Comment by inb4after** [comment] 2021-05-22 23:34
> Not trying to be a bother but just noticed now on testing Branch movie studio logos are not showing up but prior to this fix they were working 

Is it every movie? Or only some are affected?

Try more popular / more rated movies as well.

**Comment by xyzfre** [comment] 2021-05-23 00:03
Every movie is affected tried all sections

**Comment by inb4after** [comment] 2021-05-23 00:35
> Every movie is affected tried all sections 

Try exiting Kodi and restarting, make sure TMDBHelper service monitor and studio logo skin settings are enabled.

Try different addons and library items as well.

**Comment by xyzfre** [comment] 2021-05-23 02:34
> > Every movie is affected tried all sections
> 
> Try exiting Kodi and restarting, make sure TMDBHelper service monitor and studio logo skin settings are enabled.
> 
> Try different addons and library items as well.

Re-download testing Branch on now all is

**Comment by SerpentDrago** [comment] 2021-05-23 12:40
I'm also not seeing Network/Studios for movies . Will still need work :(

**Comment by SerpentDrago** [comment] 2021-05-23 13:08
Tested and working , YOU have to to be on the latest version of tmdb helper From jurials repo , and latest testing . But working perfectly here , Ready too merge !

**Comment by inb4after** [comment] 2021-05-23 14:06
Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.7

-Make sure you are on latest TMDBHelper v4.3.7+
-Enable TMDBHelper service monitor in skin miscellaneous settings
-Enable Studio icon toggle for widgetbar items

**Closed as completed by inb4after** 2021-05-23 14:06 UTC
Labels: Please test, Ready to merge

**Comment by xyzfre** [comment] 2021-05-23 18:16
I’m not sure if this is the way it is now ,,but I applied  the matrix branch and on home screen widgets ONLY for TV shows and episodes the Network logo doesn’t show up any more,, but if I go inside of a addon like TMDB or Fen TV show networks and movie Studio logos do show up and they look amazing now that you guys increase the size just wondering if they are not supposed to show up on home screen widgets ,, using AuraMod Home Layout,, Vertical Icons Only,, Nvidia shield pro K19.1,,Going to post a video in a few

**Comment by xyzfre** [comment] 2021-05-23 18:27
https://user-images.githubusercontent.com/49699869/119272130-88f1b400-bbd2-11eb-9c9b-e2a30acf82ca.MOV

As you can see in the video on the home screen widgets TV show networks don’t show up anymore,, AuraMod Home Layout, Vertical Icons Only ,,and I am using the latest version of TMDB from jurialmunkey Repo and both service monitors are enabled and studio icon toggle enabled as well

**Comment by xyzfre** [comment] 2021-05-23 19:05
https://user-images.githubusercontent.com/49699869/119273301-3d420900-bbd8-11eb-8ffb-420149f7cb2b.MOV

Seems to be only on home screen widgets everywhere else they show up fine and love the way they look now The size increase made a difference

**Comment by inb4after** [comment] 2021-05-23 21:23
@xyzfre I will look into this soon.

**Comment by xyzfre** [comment] 2021-05-23 22:39
Not infront of my Shield right now but I think it has to do with home layout style a friend uses Netflix Home Layout spoke to him briefly but I think he said they work on home screen widgets using that Layout,, but I use Aura Home Layout didn’t get a chance to test it with Netflix Home Layout

**Comment by inb4after** [comment] 2021-05-23 23:14
> 
> 
> Not infront of my Shield right now but I think it has to do with home layout style a friend uses Netflix Home Layout spoke to him briefly but I think he said they work on home screen widgets using that Layout,, but I use Aura Home Layout didn’t get a chance to test it with Netflix Home Layout

Confirmed, working on Netflix Home, but not Aura Home. Something to do with how the widgets are loading and overlapping image ID. I will have to work on it after a short break.

**Comment by xyzfre** [comment] 2021-05-23 23:18
Thank you for your response and all the hard work you guys are putting into AuraMod it’s coming along amazing

**Comment by inb4after** [comment] 2021-05-23 23:26
> 
> 
> Thank you for your response and all the hard work you guys are putting into AuraMod it’s coming along amazing

I've got a permanent fix for this, however since the logo was resized based on Netflix Home, it's much too large for this widget label. See screenshot: https://i.imgur.com/OcEYzyE.jpg

Planning to use the old logo size for Aura home, give me a few days to sort out the logistics and we can push the fix directly to Matrix branch.

**Comment by inb4after** [comment] 2021-05-24 18:17
@xyzfre Please see #102 for details of the new issue and fix.
