### ISSUE TITLE
[BUG]Episode Rating, Runtime & Liked % display issues

### ISSUE THREAD

**Issue by Dealz-416LS** [SerpentDrago/skin.auramod#36] opened 2021-04-05 20:30 UTC
The issue is Episode Rating is displayed as N/A, Runtime is displayed for a second then disappears and at the same time the Liked % 'sometimes' changes.

https://user-images.githubusercontent.com/54026944/113623081-c071c480-9655-11eb-9799-cb1e7f36244b.mp4

When looking at episode(s) via `Show > Season > Episodes` the issue occurs.
![Kodi_20210406_042058](https://user-images.githubusercontent.com/54026944/113654580-0c415f80-9690-11eb-8248-9daf606b38e3.png)

However when looking at the same episode via `My Shows > Recently Watched` there is no issue.
![Kodi_20210406_042020](https://user-images.githubusercontent.com/54026944/113654674-401c8500-9690-11eb-856d-531317cda79f.png)

Also i noticed that when you `Context menu` on an episode then short press `Browse Season` All Liked %, Rating and runtime is the same for every episode.

Kodi 19.0
Seren 2.0.18+Matrix. 1
Auramod Testing Branch

**Comment by inb4after** [comment] 2021-05-18 17:55
@Dealz-416LS 

Fixed the episode duration visibility in [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing).

However I cannot reproduce the missing MPAA. Which path exactly do you navigate to reproduce this? It might have been fixed automatically due to the ratings update. Please update to the latest Testing branch before reproducing.

The Liked % updating is due to the additional ratings appearing. It looks like the skin always prefers IMDB or RottenTomatoes ratings over the normal (faster loading) rating, which is why you see the normal rating first, then it updates to a different one. It happens on the homescreen as well. I can reverse this behaviour, as it doesn't make sense to have IMDB or RT ratings in both places on the homescreen.

Please let us know your results, and if any new bugs occur.

**Comment by Dealz-416LS** [comment] 2021-05-18 20:58
- Runtime now displayed, no longer disappearing (Fixed).

- N/A being displayed for episode rating instead of TV-MA, TV-14 etc. was user error.

**Solution** by @inb4after was to add TMDb and OMDb API keys to Seren.

- Improvements to the way % Liked is displayed is being looked into by @inb4after and @SerpentDrago [comment by SerpentDrago](https://github.com/SerpentDrago/skin.auramod/issues/60#issuecomment-828127007)

**Comment by inb4after** [comment] 2021-05-20 13:00
> 
> 
>     * Runtime now displayed, no longer disappearing (Fixed).
> 
>     * N/A being displayed for episode rating instead of TV-MA, TV-14 etc. was user error.
> 
> 
> **Solution** by @inb4after was to add TMDb and OMDb API keys to Seren.
> 
>     * Improvements to the way % Liked is displayed is being looked into by @inb4after and @SerpentDrago [comment by SerpentDrago](https://github.com/SerpentDrago/skin.auramod/issues/60#issuecomment-828127007)

After discussing with @SerpentDrago we decided to leave the code as it is currently. Visual bugs are present before a proposed change (liked % updating), as well as after (liked % disappears when in power menu/overlay). 

Changing it to a decimal "out of 10" rating misses the point as well, despite the fact that liked % isn't really a true liked %. We will leave it for now as the current system works, and there's not much we can do to satisfy everyone.

**Comment by inb4after** [comment] 2021-05-23 14:04
Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.7

**Closed as completed by inb4after** 2021-05-23 14:04 UTC
Labels: bug, High Priority, Please test, Ready to merge
