### ISSUE TITLE
Category bar labeling broken 

### ISSUE THREAD

**Issue by JFG1000** [SerpentDrago/skin.auramod#30] opened 2021-04-01 14:54 UTC
![20210401_153705](https://user-images.githubusercontent.com/76907836/113312670-6d6cda00-9302-11eb-97ac-6e41d4f1a722.jpg)

Rebuilding from scratch today and have noticed the category bar labels to not appear, i have small category bar widgets

**Comment by inb4after** [comment] 2021-04-01 16:39
Duplicate of #23

**Comment by JFG1000** [comment] 2021-04-01 16:51
It's not a duplicate, the first post states that the labeling is broken when "enable categories on widget bar" is disabled, this is currently broken regardless of it being enabled or not

**Comment by inb4after** [comment] 2021-04-01 19:36
This is how it has always been in Leia, there are not supposed to be any widget labels for the small category widget. 

The other issue you opened is lower priority and will be looked at later, but it probably won't get added until all other higher priority bugs are fixed.

**Comment by JFG1000** [comment] 2021-04-01 19:41
![20210401_134248](https://user-images.githubusercontent.com/76907836/113345516-796c9200-932a-11eb-92c3-c78a1115f880.jpg)

I'm sorry but what you have said is incorrect, it's always been a thing, my picture shows this "collection" 

This has always existed from leia onwards

**Comment by inb4after** [comment] 2021-04-01 19:43
Thanks for the screenshot, makes this so much more clear. I'll have a look soon. Please add screenshots to your other issue, to show Leia functionality as I cannot reproduce (must be missing a setting somewhere).

**Comment by JFG1000** [comment] 2021-04-01 19:46
Thankyou, and this is a screen shot from leia which i dug out, it's not broken on the matrix branch i know that for sure, i noticed it was broken on the test branch when you advised me to start from scratch earlier today as I'm currently doing

**Comment by inb4after** [comment] 2021-04-01 20:06
It seems AuraMOD has always disabled these items on first install, but it's not a bug per se. Try enabling some items under `Skin Settings > Widgets > Select WidgetBar Items`, for example "Title".

**Closed as completed by inb4after** 2021-04-01 20:06 UTC

**Comment by JFG1000** [comment] 2021-04-01 20:09
Ah brilliant thankyou, my apologies
