### ISSUE TITLE
[BUG]Issue w/ Navigation from Widget > Information

### ISSUE THREAD

**Issue by Dealz-416LS** [SerpentDrago/skin.auramod#31] opened 2021-04-01 18:08 UTC
From a Home-screen widget, clicking (short press) on the widget item takes me to the Information screen for this item but as the loading of this screen completes or very soon after it will automatically return to the home-screen before I've clicked on anything else.

Widgets are from Seren
`Skin Settings > Home > Default Select Action - Show Information` is enabled.

It's appears the issue is random and I'm not sure what triggers it.

I'll add a recording if i can manage to capture it.

I was able to capture when it happened towards/the end of this [kodi.log](https://github.com/SerpentDrago/skin.auramod/files/6245513/kodi.log)

**Comment by SerpentDrago** [comment] 2021-04-01 18:41
you are not using a mouse right ? 

Which branch are you using of auramod , and when did you get it ? 

Does it happen on any item  ? or only on that title ?

I

**Comment by Dealz-416LS** [comment] 2021-04-01 19:26
@SerpentDrago 

No Mouse
I am on the [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing), honestly it's been happening for a while, maybe from the start of AuraMOD on Matrix.
From my experience i think it can happen to any title/widget item.

**Comment by SerpentDrago** [comment] 2021-04-01 19:37
and you are using netflix info screen right ? 

![image](https://user-images.githubusercontent.com/21133858/113345092-f7677380-92ff-11eb-9363-0a759ce9a8cd.png)

![image](https://user-images.githubusercontent.com/21133858/113345319-4ad9c180-9300-11eb-902d-ba85fbb1e93c.png)


I can't replicate that . Theres other issues with video info (trakt manager button is broken , navigating to anything from cast & more locks you in . etc etc )  but no weird navigating back pre maturely

Are you sure this is not some controller plugged in or your tapping the mouse or something .. go into kodi's input settings and disable mouse / touch input completely  and controller support

**Comment by SerpentDrago** [comment] 2021-04-01 19:52
![image](https://user-images.githubusercontent.com/21133858/113346899-7067ca80-9302-11eb-93da-4a4ae1f997de.png)

**Comment by Dealz-416LS** [comment] 2021-04-01 19:54
Yes that's the info screen I am using also when i click on a widget item, I don't think it will be easy to replicate as it's random for me, i don't know what triggers it. I just use Kodi as normal and it happens from time to time.

I don't have or use a controller or mouse, I've seen that setting before. I'll turn it off if it's enabled.

**Comment by Dealz-416LS** [comment] 2021-04-01 23:20
@SerpentDrago @inb4after 

So i spent some time to try and figure out how it's happening and i can now replicate it 100% of the time on my setup.

Steps i used to reproduce.

1. `Power Menu`
2. `Settings`
3. `Back` on remote
4. Click on a Widget to navigate to Information Screen
5. Automatically sent back to home-screen
 
https://user-images.githubusercontent.com/54026944/113363079-d591df00-9347-11eb-9118-e003e5b120a4.mp4

Here is a new debug [kodi.log](https://github.com/SerpentDrago/skin.auramod/files/6246870/kodi.log) where i was able to get the issue to happening every time, I reproduced it multiple times using the steps above.

**NOTE**
This issue doesn't just happen after going to Settings, I've had it happen less consistently without going to Settings, So far Settings is the only way i can get it to happen all the time. 

**Update 1**
I added Settings to the main menu `ACTIVATEWINDOW(SETTINGS)` followed the same steps but instead accessed Settings from the Main Menu and the issue happens.

So i tried a different option `Seren Tools` in the Power Menu instead of Settings and the issue still happens! It's seems like if you navigate some where via the Power Menu the issue will happen.

I am not yet sure how it happens when i don't access Settings (Power Menu) first.

**Update 2**
It's not just items on the Power Menu, If i navigate away from the home-screen using _Power Menu items_, _Submenu Items_ or _Main Menu items_ then return to the home-screen and click on a widget the issue will happen.

Same steps but using the Submenu item.

https://user-images.githubusercontent.com/54026944/113365163-47205c00-934d-11eb-818b-ef29b65af0e1.mp4

**Comment by inb4after** [comment] 2021-04-02 00:03
Still cannot reproduce, however I noticed that it happens during the time the Youtube addon is supposed to play the trailer. Try re-toggling then disabling `Skin Settings > Library Views > Enable Video Info Trailer auto-play`. Then try your steps to reproduce again.

The re-toggle (even if it's off) is needed as it runs by default (Leia bug). This should help us narrow down the issue.

**Comment by Dealz-416LS** [comment] 2021-04-02 00:12
@inb4after I tried what you suggested re-enabling and disabling `Enable Video Info Trailer auto-play` then re-tested and the issue still happens.

**Comment by inb4after** [comment] 2021-04-02 12:21
@Dealz-416LS @jojobrogess Seems to be a problem with the TMDBHelper code in the skin being outdated (but this doesn't explain why the bug affects only some) or running too late/early. I'm not sure why we can't reproduce this issue though, and that makes it difficult to fix.

**Comment by inb4after** [comment] 2021-04-02 12:47
@Dealz-416LS @jojobrogess

I've made 4 branches of Testing branch that we can try to narrow down this issue. I do have a faint idea why this is happening but I need confirmation. 

Please test these individually and write down your result for each branch (you can install from zip, as normal):

- [test1](https://github.com/SerpentDrago/skin.auramod/tree/test1)
- [test2](https://github.com/SerpentDrago/skin.auramod/tree/test2)
- [test3](https://github.com/SerpentDrago/skin.auramod/tree/test3)
- [test4](https://github.com/SerpentDrago/skin.auramod/tree/test4)

**Comment by Dealz-416LS** [comment] 2021-04-02 13:55
@inb4after I tested all 4 branches and i was still able to reproduce the issue with navigation.

**Comment by inb4after** [comment] 2021-04-02 14:32
@Dealz-416LS Try [test5](https://github.com/SerpentDrago/skin.auramod/tree/test5). Fingers crossed.

**Comment by Dealz-416LS** [comment] 2021-04-02 14:56
@inb4after Unfortunately I was still able to reproduce the issue on test5.

Added [kodi.log](https://github.com/SerpentDrago/skin.auramod/files/6250181/kodi.log)

**Comment by Dealz-416LS** [comment] 2021-04-02 19:33
I wiped Kodi and started fresh, however I didn't touch any settings in AuraMOD expect the Setup Wizard - Home style, Submenu widget size and skipped Spotlight setup. First thing i did was setup a main menu item for a widget to test and i was able to reproduce the navigation bug. I also added a widget from TMDb Helper (In case it was an issue w/ Seren widgets) but again was able to reproduce.

**Comment by inb4after** [comment] 2021-04-02 20:47
Does this happen when you `Context menu > Information` instead of short press?

**Comment by SerpentDrago** [comment] 2021-04-02 20:59
@Dealz-416LS  What style Home menu are you using ? have you tried changing the home menu style to something other then a netflix one ? also what style power menu ? 

Also after trying the test branches , it may be needed to rebuild the menus and restart kodi ? ? 

Do you have youtube configured with api key ? 

Just trying to figure out what is different in your setup vs ours .

can you zip up your kodi folder and send it to us ?

**Comment by Dealz-416LS** [comment] 2021-04-02 21:21
@inb4after @SerpentDrago 

I am 100% sure it's a speed/timing issue.

inb4after suggested i test using context menu and i did, I found it inconsistent if the issue happened so i was wondering why when it was 100% reproducible with my previous steps... It's because the time it takes to bring up the context menu and then short press Information various if i do it to quick i get the issue, if i am slightly to long i don't.

It also explain why i can reproduce it 100% of time, during testing i can do the steps quick and also explain why i found it so random at first when i didn't understand how it happened.

@SerpentDrago 
Netflix Home Layout
Yes I've tried all 3 home styles
The standard power menu style 
Rebuild happens automatically after the update, I've tried a Kodi restart.
Yes to Youtube API

**Comment by SerpentDrago** [comment] 2021-04-02 21:29
Ok i managed to make it happen like 1 time . I have a fucking 8700k @ 5ghz , 12 gigs of ddr4 3200mhz ram , and a 970evo+ nvme .

and i can't go THAT fucking fast to make it happen .. except 1 time .. 

slow down haha

Sounds like the skin is still backing out of stuff when you pull up netflix info . thous it goes back home .. prob some timer to prevent other issues purposely slowing down the skin

**Comment by SerpentDrago** [comment] 2021-04-02 21:32
Ok i can get it to happen but i have to be like FUCKING stupid fast to the point i'm hitting back (backspace) then RIGHT AWAY hitting enter before i can even barely see the widgets / home screen ...

Seriously .. just slow down . I mean damn i can navigate this entire skin fast .. but even then i wait for things to appear on screen first ..

**Comment by Dealz-416LS** [comment] 2021-04-02 21:34
> 
> 
> Ok i managed to make it happen like 1 time . I have a fucking 8700k @ 5ghz , 12 gigs of ddr4 3200mhz ram , and a 970evo+ nvme .
> 
> and i can't go THAT fucking fast to make it happen .. except 1 time ..
> 
> slow down haha

LOL, hmm when it was happening randomly during normal use i didn't feel like i was navigating to fast, I'm using a Shield. but yes i also think on returning to the home-screen i go into a widget before the home-screen has fully loaded in the background and it forces me back.

I've posted a couple of video clips (@inb4after has seen a couple of others) and i don't feel like the navigation was too fast, the home-screen on return has loaded.

**Comment by SerpentDrago** [comment] 2021-04-02 21:36
yeh your not having to navigate as fast as me . mybee the solution is to make auramod default t the menu instead of a widget when going back home .. like slow down the user just a tad ..

**Comment by Dealz-416LS** [comment] 2021-04-02 21:43
@SerpentDrago Yes, That should work. By the time the user gets to the target widget from the main menu and short presses it everything should have loaded, so being forced back to the home-screen shouldn't happen.

On return to the home-screen, I had to wait 3-4 seconds to avoid reproducing the issue.

**Comment by Dealz-416LS** [comment] 2021-04-02 23:28
@SerpentDrago I done a quick test just to make sure i didn't have to much on my home-screen so i disabled pretty much everything, all that was left was 1 main menu item, which had 1 row of widgets with only 1 widget item in that row and i was still able to reproduce the issue.

**Comment by SerpentDrago** [comment] 2021-05-06 18:42
Unable to really replicate this issue , "it randomly exiting / going back from netflix info " 

I'm closing this for now , if it pops up again from someone else or we get more details feel free to open a new issue . 

Without a reliable way to replicate and confirmation from someone normally navigating around "not going stupid fast" there is just nothing that can really be done , mybee it will just fix itself once other stuff with info is fixed ? 

Thanks !

**Closed as completed by SerpentDrago** 2021-05-06 18:42 UTC
Labels: Not Reproducible
