### ISSUE TITLE
Spotlight Mobie titles disappeared.

### ISSUE THREAD

**Issue by adamosborne83** [SerpentDrago/skin.auramod#107] opened 2021-05-27 18:13 UTC
Hey sorry,

See the video below, again all of a sudden the title of the movies or TV shows on spotlight has disappeared.

I've tried clearing cache etc still no good.

http://imgur.com/a/N0EebIa

**Comment by SerpentDrago** [comment] 2021-05-27 21:36
This is 100 percent related to your other artwork issue post

**Comment by inb4after** [comment] 2021-05-28 04:18
Closed, probable duplicate of #106 and most likely not an AuraMOD issue as we cannot reproduce.

**Closed as completed by inb4after** 2021-05-28 04:18 UTC
Labels: duplicate, Low Priority, Not Reproducible
