### ISSUE TITLE
Top widget row displays at the bottom of the screen when no subcategory widgets are enabled

### ISSUE THREAD

**Issue by Hannan100** [SerpentDrago/skin.auramod#208] opened 2021-10-10 20:03 UTC
I recently disabled all my submenus after realising that I just don't use them and now maybe 90% of the time when I'm selecting an item in the top row the screen scrolls the row half way off the bottom with a big blank space up top.

https://user-images.githubusercontent.com/4128798/136711064-0eff7b44-89ce-4f03-9cb1-6df0e202936c.mp4

Kodi 19.2 
Auramod 1.0.32
Nvidia Shield Pro

**Comment by inb4after** [comment] 2021-12-11 12:04
I think this bug has already been fixed. 

Please test the latest version of AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.1.3

**Comment by xbmcnut** [comment] 2021-12-12 02:55
I have the same issue on all releases past  v1.0.36. Only way to fix is to change menu from Horizontal to Vertical as a workaround.

**Comment by inb4after** [comment] 2021-12-12 14:24
> I have the same issue on all releases past v1.0.36. Only way to fix is to change menu from Horizontal to Vertical as a workaround.

Could you record a short video of v1.1.3 showing the homescreen having the large gap, changing it to Vertical layout and a quick overview of all skin settings?

**Comment by inb4after** [comment] 2021-12-12 14:42
@Hannan100 @xbmcnut 

Found the bug, you must change category widget size to medium or large before disabling category widgets. If you leave it as small, it will cause this gap.

**Comment by xbmcnut** [comment] 2021-12-13 03:05
I found a workaround too by setting the menu to vertical and then back to horizontal (with categories on medium) and it seems to be working now.

**Comment by inb4after** [comment] 2021-12-15 17:29
> I found a workaround too by setting the menu to vertical and then back to horizontal (with categories on medium) and it seems to be working now.

Gotcha. The major changes to the submenu layout probably just required a quick settings change for it to work properly as you have experienced.

**Comment by xbmcnut** [comment] 2021-12-15 23:51
Sadly, I still have the issue. Even after making the settings changes, the large gap at the top returns after a while if you disable category widgets (even with them set to med or lge before turning off). I've had to turn categories back on which is less than ideal so let me know what I can provide to assist with a debug. Version I'm running is 1.1.4

**Comment by inb4after** [comment] 2021-12-16 00:06
> Sadly, I still have the issue. Even after making the settings changes, the large gap at the top returns after a while if you disable category widgets (even with them set to med or lge before turning off). I've had to turn categories back on which is less than ideal so let me know what I can provide to assist with a debug. Version I'm running is 1.1.4

I have reproduced with category widgets disabled on the new version, reopening this as high priority.

**Comment by xbmcnut** [comment] 2021-12-16 03:05
Thank you, really appreciate that. When it does glitch out and you navigate down to the main widgets, its not possible to navigate back up to the main menu 99% of the time. Up and down only goes up and down the widgets. Pushing ESC allows you to get to the main menu but its not intuitive.

**Comment by Goldenfreddy0703** [comment] 2021-12-16 14:17
Hey @Hannan100, I found a solution around that, if you Enable Categories Widget, then go to Customize Home Menu & Widgets and go on Configure Submenu / Category Widget on that main menu item, you can disable all the submenu widgets one by one and that should fix the issue you were having. 

Sure it's still a bug but i found a workaround for that.
Hope this helps.

**Comment by inb4after** [comment] 2021-12-16 22:49
Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.1.5

**Closed as completed by inb4after** 2021-12-16 22:49 UTC
Labels: bug, High Priority

**Comment by xbmcnut** [comment] 2021-12-16 23:30
Legend! Thank you so much.
