### ISSUE TITLE
[BUG]Issue w/ Navigation in Cast & More

### ISSUE THREAD

**Issue by Dealz-416LS** [SerpentDrago/skin.auramod#16] opened 2021-03-24 20:09 UTC
I mentioned this bug in a different issue but i thought it might be best to have it's on issue created.

IIRC It was said, that issue was due to an update to TMDb Helper that broke the exiting implementation with it and AuraMOD which is likely the cause of this issue.

The issue is when you go to the information screen then 'Cast & More' everything is fine initially when you navigate into it (information, cast images, show posters etc load just fine, even the cast/show/movie information screen themselves loads fine). But if you click on any of them then try to navigate back you get stuck in a loop and end up stuck on the cast/show/movie information screen that you clicked on.

While trying to navigate back i have experienced an infinite loading (busy dialog notification), TMDb Helper error and Kodi crash

I've gotten this bugged screen sometimes.
![Kodi_20210324_195405](https://user-images.githubusercontent.com/54026944/112375184-e654ac00-8cda-11eb-8c2a-d97a45f0bc2c.png)

Kodi: 19.0 Matrix
Seren: 2.0.17+Matrix. 1
TheMovieDb Helper 4.3.1
Auramod: 1.0.3.3

[kodi.log](https://github.com/SerpentDrago/skin.auramod/files/6199999/kodi.log)

**Comment by SerpentDrago** [comment] 2021-03-24 21:46
noticed this today when playing around , Def some weird ass bug

**Comment by adamosborne83** [comment] 2021-04-06 16:50
Glad it's not just me, I thought it was something I did as couldn't get any help in Reddit.
Hopefully fixed soon, as a good feature to have

**Comment by SerpentDrago** [comment] 2021-05-06 18:43
Figured i'd give a update . 
This bug is proving a bitch to solve , inbafter  narrowed it down a lot , but its going to take a time .

This bug also happen on Kodi 18 , it started appearing once tmdb helper v4 was released. Something changed breaking auramod's ability to reload and go back to previous info screens . 

Once this bug is solved most of the skin would be what i consider a "usable condition" so understand its on the top of the list .

Wish him luck !

**Comment by adamosborne83** [comment] 2021-05-06 18:54
Cheers for the update, this is deffo the only major bug that I've noticed with the skin, thanks guys for doing what you can

**Comment by inb4after** [comment] 2021-05-09 04:57
@Dealz-416LS @SerpentDrago @adamosborne83 

Fixed in [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing).

Tests passed:

- [x] Actor info from the first movie/show/episode level
- [x] Actor info from the subsequent levels
- [x] Video info from Similar, Recommended, By Genre etc. from the first movie/show/episode level
- [x] Video info from Similar, Recommended, By Genre etc. from the subsequent levels

Please let us know your results and if any further bugs occur.

**Comment by adamosborne83** [comment] 2021-05-09 07:56
Seems to be working fine, I got through to about 10 different movies from the 'similar button and I was beginning to lag when I would press the back button, but this was just me trying to break it as such, to which I didn't, and works great!
Thabk you so much, you peeps have been bloody busy this week! Bravo 👏

**Comment by adamosborne83** [comment] 2021-05-09 08:18
Just noticed all my watched indicators no longer show on my widgets on the home screen. When I go into the folder for example Most Popular on Seren or Venom, they are there.

**Comment by inb4after** [comment] 2021-05-09 16:48
> 
> 
> Just noticed all my watched indicators no longer show on my widgets on the home screen. When I go into the folder for example Most Popular on Seren or Venom, they are there.

Is this a result of the new update? (Does it fix itself when you go back to [Matrix branch](https://github.com/SerpentDrago/skin.auramod/)?)

Tested both Movies and TV shows and marking as watched (in Seren Trakt Manager, not the default Kodi context menu option) does give the watched tick (after a skin reload of course), therefore I cannot reproduce this bug. Screenshots would definitely help.

Please open a new issue and upload screenshots of all situations you have tested, as I cannot reproduce the bug without first knowing what it looks like.

Thanks in advance.

**Comment by adamosborne83** [comment] 2021-05-09 17:09
Yea, this is a result of the testing branch.

I will uploads some pics later.
Thanks in advance

**Comment by inb4after** [comment] 2021-05-11 06:57
@adamosborne83 

Are you still having issues with watched indicators on [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing) vs [Matrix branch](https://github.com/SerpentDrago/skin.auramod/)?

**Comment by adamosborne83** [comment] 2021-05-11 07:20
@inb4after 
On my firecube it's fine, but in my bedroom on forestick it's happening, so obviously a it's something to do with me.

Thabk you for fixing this

**Comment by inb4after** [comment] 2021-05-11 08:00
> 
> 
> @inb4after
> On my firecube it's fine, but in my bedroom on forestick it's happening, so obviously a it's something to do with me.
> 
> Thabk you for fixing this

Thanks for the reply. As long as both devices are running the same branch and the issue is not affecting both, I think we're good to go.

Check if Skin Settings > Library Views > Watched indicators are enabled (it might be this simple, or maybe something else is affecting it, in which case screenshots and video would help a lot)

**Comment by adamosborne83** [comment] 2021-05-11 16:02
Something odd is happening, see the video below hopefully it explains it better than I can. 

http://imgur.com/a/Z2F0ydM

**Comment by SerpentDrago** [comment] 2021-05-11 16:11
Its normal for it to flash back to last screen before opening up the New info page . then when you go back it will flash and load the last info page you were on .

**Comment by adamosborne83** [comment] 2021-05-11 16:21
> Its normal for it to flash back to last screen before opening up the New info page . then when you go back it will flash and load the last info page you were on .

Cheers for the reply, I guessed that, but if you see I clicked on the Girl, and the previous character I clicked on the bloke came up and then it crashed back to the hone screen as such and dis not show the girls info.
Hope that makes sense

**Comment by SerpentDrago** [comment] 2021-05-11 16:51
Roger , closing this issue , and inb4after made a new one specifically addressing this . 

Everything else should be fixed with the org cast & more navigation issues in matrix branch version 1.0.5

**Closed as completed by SerpentDrago** 2021-05-11 16:51 UTC
Labels: bug, help wanted, High Priority, Please test

**Comment by inb4after** [comment] 2021-05-11 16:53
Mostly fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.5

Discussion of this bug has moved to #88 as the cause is slightly different to what was tested/originally seen.
