### ISSUE TITLE
[BUG]Rating/Studio logo displayed for See More widget

### ISSUE THREAD

**Issue by Dealz-416LS** [SerpentDrago/skin.auramod#103] opened 2021-05-25 15:23 UTC
Minor issue, ratings and/or Studio logo is displayed for the see more widget on the homescreen using Netflix Home Style.

![image](https://user-images.githubusercontent.com/54026944/119524188-546a2d80-bd75-11eb-8666-48ed89cb9d4f.jpeg)

Auramod 1.0.9 (Matrix Branch)

**Comment by SerpentDrago** [comment] 2021-05-25 16:09
This has always been the case , and its more like its stuck with whatever last rating you pulled up typically. always happened . it would be a feature request to change this

**Comment by inb4after** [comment] 2021-05-25 16:20
Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.10

Could not reproduce studio appearing, but we'll keep an eye on this and revisit if needed. The screenshot above was most likely taken on v1.0.7 which was before the big studio patch.

**Comment by Dealz-416LS** [comment] 2021-05-25 16:21
Looks like the studio logo was unintentionally fixed with one of the recent changes as I'm no longer seeing this issue (took the screenshot a few days ago) and @inb4after is unable to replicate.

@inb4after was able to remove the red star rating.

**Closed as completed by inb4after** 2021-05-25 16:20 UTC
Labels: bug, enhancement, Low Priority
