### ISSUE TITLE
Crashes when stopping playback

### ISSUE THREAD

**Issue by ryadre** [SerpentDrago/skin.auramod#33] opened 2021-04-05 08:41 UTC
Kodi crashes when stopping playback quite often
Shield 2019
Kodi 19

**Comment by notownblues** [comment] 2021-04-05 10:35
I can confirm it crashes very often on Kodi 19 Shield TV here too

**Comment by Dealz-416LS** [comment] 2021-04-05 13:20
Do either of you have Language Invoker enabled? Assuming your using Seren.

`Seren Tools > Open Settings Menu > Shortcuts > Language Invoker Options`

**Comment by notownblues** [comment] 2021-04-05 13:28
> Do either of you have Language Invoker enabled? Assuming your using Seren.
> 
> `Seren Tools > Open Settings Menu > Shortcuts > Language Invoker Options`

Yes it's enabled on my side. Kodi doesn't crash when playback is paused or stopped for me but it does 90% of the time after inactivity for X minutes (don't have an exact number, it's mostly after a long delay but can be after 20 mins sometimes). Also, if I open Netflix on Shield TV and then open Kodi again it crashes and has to start and load widgets again.

**Comment by Dealz-416LS** [comment] 2021-04-05 13:51
@notownblues I recommend you disable it, That setting causes instability in some devices, in my experience using a Shield if I have it enabled I will get Kodi crashes.

**Comment by notownblues** [comment] 2021-04-05 13:52
> @notownblues I recommend you disable it, That setting causes instability in some devices, in my experience using a Shield if I have it enabled I will get Kodi crashes.

Thank you so much 🙏🏻 I'll try that and see how it goes.

**Comment by notownblues** [comment] 2021-04-05 22:39
> @notownblues I recommend you disable it, That setting causes instability in some devices, in my experience using a Shield if I have it enabled I will get Kodi crashes.

Unfortunately Kodi still crashes every time I use another app for some time and get back to it even after disabling Language Invoker. It basically can't run in the background anymore. I have everything Off in Power Saving so I think it might be coming from the skin.

**Comment by ryadre** [comment] 2021-04-05 22:57
I dont have any of those addons installed, I only have a few installed. I have Composite (plex addon) and premiumize, and keymap editor, and EZ Maintenance +

**Comment by Dealz-416LS** [comment] 2021-04-05 23:56
@notownblues Unfortunately there is something else going on with your set up, I've not had any issue with persistent crashing.

The overall amount of crashes should still be reduced with `Language Invoker` disabled as is does cause crashing on Nvidia Shield.

@ryadre @notownblues I suggest you go to Kodi `Settings > System > Logging > Enable debug logging` Checked, so that the crash can be captured with debug.

Then upload the kodi.log here so someone with the knowledge can have a look at it.

**Comment by notownblues** [comment] 2021-04-06 07:10
> @notownblues Unfortunately there is something else going on with your set up, I've not had any issue with persistent crashing.
> 
> The overall amount of crashes should still be reduced with `Language Invoker` disabled as is does cause crashing on Nvidia Shield.
> 
> @ryadre @notownblues I suggest you go to Kodi `Settings > System > Logging > Enable debug logging` Checked, so that the crash can be captured with debug.
> 
> Then upload the kodi.log here so someone with the knowledge can have a look at it.

Thanks for your help @Dealz-416LS. I've actually already had a look at the logs myself but it's hard to see the exact reason when you're not a developer 😅 It's a bit tricky to export from the Shield but I'll find a way because it's such a brilliant skin and a shame it crashes that often since the new version so if it could help to resolve the issues it'd be amazing. Thanks for your support again. Where would be the best place to upload them? On this thread? It might be quite a big file.

**Comment by Dealz-416LS** [comment] 2021-04-06 13:46
Yes your right, I'll have a look at the log purely out of curiosity but actually understanding what's going on I will leave that to the experts. I agree the skin is brilliant and it would be good to understand why Kodi is crashing in your setup with the skin.

No problem, you can attach it here and file size shouldn't be an issue if it is you can always upload the file else where and link to it.

**Comment by notownblues** [comment] 2021-04-06 15:40
> Yes your right, I'll have a look at the log purely out of curiosity but actually understanding what's going on I will leave that to the experts. I agree the skin is brilliant and it would be good to understand why Kodi is crashing in your setup with the skin.
> 
> No problem, you can attach it here and file size shouldn't be an issue if it is you can always upload the file else where and link to it.

@Dealz-416LS I've attached my 2 log files. Hope it helps :) 

[Kodi Old Log.txt](https://github.com/SerpentDrago/skin.auramod/files/6265856/Kodi.Old.Log.txt)
[Kodi Log.txt](https://github.com/SerpentDrago/skin.auramod/files/6265857/Kodi.Log.txt)

**Comment by ryadre** [comment] 2021-04-07 08:23
I switched to amber skin, and still had kodi crash when playback stopped, so must be something else causing it

**Comment by xyzfre** [comment] 2021-04-07 20:30
> I switched to amber skin, and still had kodi crash when playback stopped, so must be something else causing it

This might work might not but it doesn’t hurt to try go into Kodi player settings and change Adjust display refresh rate and set that to ALWAYS  power down Kodi and restart it and see if it crashes again,, I suggest this because I had a friend having similar issues and this seem to help,, Good luck hope it works🤞🏼

**Comment by SerpentDrago** [comment] 2021-04-08 14:07
Closing this as its not a Auramod issue , thanks

**Closed as completed by SerpentDrago** 2021-04-08 14:07 UTC
